In [1]:
# importing important library
import pandas as pd
import re
from sklearn.model_selection import train_test_split
# importing drive so that we can bring our files mainly data that is in fnd file
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
# loading our true dataset

true_df = pd.read_csv("/content/drive/MyDrive/Fake News Detection /Processed Data/True.csv")

# now we have loaded our dataset and lets try to see our data

true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [4]:
#loading our fake dataset

fake_df = pd.read_csv("")

# lets see the data

fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
# we are adding label to fake news and real news
true_df['label']=1
fake_df['label']=0
# seeing the data after adding label
true_df.head()

In [ ]:
# combining title + text
# kaggle dataset has title text subject date
true_df['content']= true_df['title']+" "+true_df['text']
true_df.head()

In [ ]:
fake_df['content']= fake_df['title']+" "+fake_df['text']

In [ ]:
# merging both datasets i.e true.csv and fake.csv
df = pd.concat([true_df,fake_df],axis=0)
df.head()
df.tail()

In [ ]:
# finding no of rows and column
df.shape

In [ ]:
# we are keeping only required columns
df = df[['content','label']]
df.head()

In [ ]:
# giving proper index and making change in original dataframe (inplace = true)
df.reset_index(drop=True, inplace=True)

In [ ]:
#Removes rows where content is empty or null
# Important because ML models cannot process empty values
df.dropna(inplace=True)

In [ ]:
# light text cleaning (transformer friendly)
# defining a cleaning function
def clean_text(text):
    text = text.lower()
    # http se start hone wala link delete ho jayega jab tak space na aaye
    # re is regular expression for handling text
    # re.sub(pattern, replacement, string) format .. sub is substitute ya replacement
    text = re.sub(r"http\S+", "", text)
    # Letters aur space ke alawa jo bhi hoga (numbers, symbols, punctuation) sab delete ho jayega
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    # extra space ko single space me convert kar rhe hai
    text = re.sub(r"\s+", " ", text)
    # removing starting and ending spaces
    return text.strip()

In [ ]:
df['content'] = df['content'].apply(clean_text)
# viewing
df['content'].head()

In [ ]:
# shuffling the data to maintain bias
# frac =1 means selecting 100% of rows random_state
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
# train test part
X = df['content']
y = df['label']

In [ ]:
# we have to divide the dataset 80 percent training 20 percent testing
# ab humare pass content aur label hai to content me v do part banenge kuch part training ke liye aur kuch part testing ke liye same for label also
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
) # we are writing x and y here so that they get splitted correctly means x ka ek row uske corresponding label ke saath hi rhe
# stratify is being used here to maintain class distribution means agar humare orginal dataset me 70 % true 30 % fake hai to train and test me v composition same hi honi chahiye
#  to ensures that there should not be any data imbalance
# We care about balancing Fake vs Real, not text values
train_df = pd.DataFrame({'content': X_train, 'label': y_train})
test_df  = pd.DataFrame({'content': X_test, 'label': y_test})
# created a new clean dataset
# now we are saving our cleaned datasets
train_df.to_csv("/content/drive/MyDrive/Fake News Detection /Data/train_dataset.csv", index=False)
test_df.to_csv("/content/drive/MyDrive/Fake News Detection /Data/test_dataset.csv", index=False)